# Generated by Django 4.1.7 on 2023-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paloma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edad", models.IntegerField(null=True)),
                ("color", models.CharField(max_length=50)),
                ("habitad", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "palomas",
            },
        ),
    ]
